// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://guhomwdnwyiyyahwzlxx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd1aG9td2Rud3lpeXlhaHd6bHh4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5NDM5OTMsImV4cCI6MjA2OTUxOTk5M30.5EpmoWDxzLN3faW258SC1OZx0EOy89xi6TSs4WnhcVA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});